/**
 * Development seed data.
 *
 * This is DEMO DATA, not real results. Every seeded account is created with the email
 * domain `@demo.badminton.local` and the marker below, so it is impossible to confuse
 * a seeded account with a real one, and `npm run db:seed` refuses to run against a
 * production database.
 *
 * The data is generated to exercise the analytics rather than to look pretty: it
 * contains winning and losing streaks, comebacks, collapses, deuce games, blowouts,
 * singles and doubles, several venues and partners, a decline in performance late in
 * long sessions, and roughly eight months of history so month-over-month trends have
 * something to show.
 */
import { PrismaClient, type Discipline, type Prisma, type SessionType } from '@prisma/client';
import { scrypt as scryptCallback, randomBytes } from 'node:crypto';
import { DEFAULT_SCORING_RULES } from '@badminton/contracts';
import { deriveMatch, replayRatings, ratingDeviation } from '@badminton/analytics';

const prisma = new PrismaClient();

const DEMO_EMAIL = 'demo@demo.badminton.local';
const DEMO_PASSWORD = 'demo-badminton-2026';
const DEMO_MARKER = 'DEMO DATA — generated by prisma/seed.ts. Not real match results.';

/** Deterministic PRNG so re-seeding produces the same database. */
function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state * 1_664_525 + 1_013_904_223) >>> 0;
    return state / 0x1_0000_0000;
  };
}

const random = makeRandom(20260816);

function pick<T>(items: readonly T[]): T {
  return items[Math.floor(random() * items.length)]!;
}

function between(min: number, max: number): number {
  return Math.floor(random() * (max - min + 1)) + min;
}

async function hashPassword(password: string): Promise<string> {
  const N = 2 ** 16;
  const r = 8;
  const p = 1;
  const salt = randomBytes(16);
  const derived = await new Promise<Buffer>((resolve, reject) => {
    scryptCallback(password, salt, 64, { N, r, p, maxmem: 256 * N * r }, (error, key) => {
      if (error) reject(error);
      else resolve(key);
    });
  });
  return ['scrypt', N, r, p, salt.toString('base64url'), derived.toString('base64url')].join('$');
}

/**
 * Generates a plausible game result given a target win probability.
 * Produces deuce games, comfortable wins and the occasional blowout.
 */
function generateGame(winProbability: number): { myScore: number; opponentScore: number } {
  const iWin = random() < winProbability;
  const roll = random();

  if (roll < 0.12) {
    // Deuce: 22-20 through 26-24, or the cap.
    const winner = 21 + between(1, 5);
    const loser = winner - 2;
    return iWin
      ? { myScore: winner, opponentScore: loser }
      : { myScore: loser, opponentScore: winner };
  }

  if (roll < 0.28) {
    // Blowout.
    const loser = between(4, 10);
    return iWin ? { myScore: 21, opponentScore: loser } : { myScore: loser, opponentScore: 21 };
  }

  const loser = between(11, 19);
  return iWin ? { myScore: 21, opponentScore: loser } : { myScore: loser, opponentScore: 21 };
}

/** Plays a best-of-three to completion at the given per-game win probability. */
function generateMatch(winProbability: number): Array<{ myScore: number; opponentScore: number }> {
  const games: Array<{ myScore: number; opponentScore: number }> = [];
  let mine = 0;
  let theirs = 0;

  while (mine < 2 && theirs < 2 && games.length < 3) {
    const game = generateGame(winProbability);
    games.push(game);
    if (game.myScore > game.opponentScore) mine += 1;
    else theirs += 1;
  }

  return games;
}

async function main(): Promise<void> {
  const databaseUrl = process.env.DATABASE_URL ?? '';
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Refusing to seed: NODE_ENV is production.');
  }
  if (/(^|[^a-z])prod([^a-z]|$)/i.test(databaseUrl)) {
    throw new Error('Refusing to seed: DATABASE_URL looks like a production database.');
  }

  console.info('Seeding demo data…');

  // Start from a clean demo account so re-seeding is idempotent, without touching any
  // other account that may exist in the same database.
  const existing = await prisma.user.findUnique({ where: { email: DEMO_EMAIL } });
  if (existing) {
    await prisma.user.delete({ where: { id: existing.id } });
    console.info('  removed the previous demo account');
  }

  const user = await prisma.user.create({
    data: {
      email: DEMO_EMAIL,
      passwordHash: await hashPassword(DEMO_PASSWORD),
      name: 'Demo Player',
      timeZone: 'Europe/London',
      emailVerified: true,
      profile: {
        create: {
          playingLevel: 'INTERMEDIATE',
          preferredDiscipline: 'DOUBLES',
          dominantHand: 'RIGHT',
          playingStyle: 'ATTACKING',
          preferredRacket: 'Yonex Astrox 88D',
          preferredStrings: 'BG65 @ 24lb',
          notes: DEMO_MARKER,
        },
      },
    },
  });

  const self = await prisma.player.create({
    data: {
      userId: user.id,
      name: user.name,
      normalizedName: user.name.toLowerCase(),
      relationship: 'SELF',
      isSelf: true,
      linkedUserId: user.id,
    },
  });

  // --- Address book --------------------------------------------------------
  const peopleSpec = [
    { name: 'John Carter', relationship: 'REGULAR_OPPONENT', strength: 0.52, level: 'ADVANCED' },
    { name: 'Ahmed Rahim', relationship: 'REGULAR_PARTNER', strength: 0.62, level: 'INTERMEDIATE' },
    { name: 'Priya Nair', relationship: 'FRIEND', strength: 0.58, level: 'INTERMEDIATE' },
    { name: 'Marcus Webb', relationship: 'REGULAR_OPPONENT', strength: 0.38, level: 'COMPETITIVE' },
    { name: 'Lena Fischer', relationship: 'FRIEND', strength: 0.66, level: 'IMPROVER' },
    { name: 'Sam Okafor', relationship: 'REGULAR_PARTNER', strength: 0.55, level: 'INTERMEDIATE' },
    { name: 'Yuki Tanaka', relationship: 'FRIEND', strength: 0.48, level: 'ADVANCED' },
    { name: 'Tom Bright', relationship: 'OTHER', strength: 0.72, level: 'BEGINNER' },
    { name: 'Coach Diane', relationship: 'COACH', strength: 0.3, level: 'ELITE' },
  ] as const;

  const people = await Promise.all(
    peopleSpec.map((person) =>
      prisma.player.create({
        data: {
          userId: user.id,
          name: person.name,
          normalizedName: person.name.toLowerCase(),
          relationship: person.relationship,
          playingLevel: person.level,
          dominantHand: pick(['RIGHT', 'RIGHT', 'RIGHT', 'LEFT'] as const),
          playingStyle: pick(['ATTACKING', 'DEFENSIVE', 'ALL_ROUND', 'FAST_FLAT'] as const),
          notes: DEMO_MARKER,
        },
      }),
    ),
  );

  const strengthOf = new Map(
    people.map((player, index) => [player.id, peopleSpec[index]!.strength]),
  );

  // --- Venues --------------------------------------------------------------
  const venueSpec = [
    { name: 'Riverside Sports Hall', city: 'London', courts: 8, favourite: true },
    { name: 'Northgate Leisure Centre', city: 'London', courts: 6, favourite: false },
    { name: 'Kingsway Badminton Club', city: 'Reading', courts: 4, favourite: false },
  ];

  const venues = await Promise.all(
    venueSpec.map((venue) =>
      prisma.venue.create({
        data: {
          userId: user.id,
          name: venue.name,
          normalizedName: venue.name.toLowerCase(),
          city: venue.city,
          country: 'GB',
          isIndoor: true,
          courtCount: venue.courts,
          isFavourite: venue.favourite,
          notes: DEMO_MARKER,
        },
      }),
    ),
  );

  // --- Sessions and matches ------------------------------------------------
  const sessionTypes: SessionType[] = ['CASUAL', 'CASUAL', 'CASUAL', 'COMPETITIVE', 'TRAINING'];
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  let totalMatches = 0;
  const dayOffsets: number[] = [];
  // Roughly twice a week for eight months, with a gap in the middle to give the
  // inactivity insight and the heatmap something real to show.
  for (let week = 34; week >= 0; week -= 1) {
    if (week >= 18 && week <= 21) continue;
    dayOffsets.push(week * 7 + 2);
    if (random() < 0.7) dayOffsets.push(week * 7 + 5);
  }

  for (const [index, offset] of dayOffsets.entries()) {
    const date = new Date(today.getTime() - offset * 86_400_000);
    const venue = index % 5 === 0 ? venues[1]! : index % 7 === 0 ? venues[2]! : venues[0]!;
    const sessionType = pick(sessionTypes);

    const startedAt = new Date(date.getTime() + 19 * 3600 * 1000);
    const matchCount = between(2, 6);
    const endedAt = new Date(startedAt.getTime() + matchCount * 40 * 60 * 1000);

    const session = await prisma.session.create({
      data: {
        userId: user.id,
        date,
        venueId: venue.id,
        sessionType,
        startedAt,
        endedAt,
        notes: index % 6 === 0 ? `${DEMO_MARKER} Felt sharp on the smash tonight.` : null,
      },
    });

    for (let order = 1; order <= matchCount; order += 1) {
      const discipline: Discipline =
        random() < 0.55 ? 'DOUBLES' : random() < 0.7 ? 'SINGLES' : 'MIXED_DOUBLES';

      const opponentCount = discipline === 'SINGLES' ? 1 : 2;
      const chosen = new Set<string>();
      while (chosen.size < opponentCount) chosen.add(pick(people).id);
      const opponentIds = [...chosen];

      let partnerId: string | null = null;
      if (discipline !== 'SINGLES') {
        const candidates = people.filter((player) => !chosen.has(player.id));
        partnerId = pick(candidates).id;
      }

      // Base strength from the opposition, improving slowly over the period, with a
      // deliberate late-session decline so the fatigue view has a real signal.
      const opposition =
        opponentIds.reduce((total, id) => total + (strengthOf.get(id) ?? 0.5), 0) /
        opponentIds.length;
      const improvement = ((dayOffsets.length - index) / dayOffsets.length) * 0.12;
      const fatiguePenalty = order >= 4 ? 0.14 : order === 3 ? 0.05 : 0;
      const winProbability = Math.max(
        0.12,
        Math.min(0.88, opposition + improvement - fatiguePenalty),
      );

      const games = generateMatch(winProbability);
      const derived = deriveMatch({ games, scoring: DEFAULT_SCORING_RULES });

      const tags: Prisma.MatchTagCreateWithoutMatchInput[] = [];
      if (order >= 4 && random() < 0.5) tags.push({ tag: 'FATIGUE' });
      if (derived.result === 'WIN' && random() < 0.3) tags.push({ tag: 'STRONG_ATTACK' });
      if (derived.result === 'LOSS' && random() < 0.35) tags.push({ tag: 'UNFORCED_ERRORS' });
      if (discipline !== 'SINGLES' && derived.result === 'WIN' && random() < 0.25) {
        tags.push({ tag: 'GREAT_TEAMWORK' });
      }

      await prisma.match.create({
        data: {
          userId: user.id,
          sessionId: session.id,
          playedAt: new Date(startedAt.getTime() + (order - 1) * 40 * 60 * 1000),
          orderInSession: order,
          discipline,
          durationSeconds: between(18, 48) * 60,
          pointsToWin: DEFAULT_SCORING_RULES.pointsToWin,
          winBy: DEFAULT_SCORING_RULES.winBy,
          maxPoints: DEFAULT_SCORING_RULES.maxPoints,
          bestOf: DEFAULT_SCORING_RULES.bestOf,
          difficulty: between(1, 5),
          energyLevel: order >= 4 ? between(1, 3) : between(3, 5),
          confidence: between(2, 5),
          feeling: between(2, 5),
          result: derived.result,
          gamesWon: derived.gamesWon,
          gamesLost: derived.gamesLost,
          pointsScored: derived.pointsScored,
          pointsConceded: derived.pointsConceded,
          pointDifferential: derived.pointDifferential,
          games: {
            create: games.map((game, gameIndex) => ({
              gameNumber: gameIndex + 1,
              myScore: game.myScore,
              opponentScore: game.opponentScore,
            })),
          },
          participants: {
            create: [
              { playerId: self.id, side: 'HOME', isSelf: true },
              ...(partnerId ? [{ playerId: partnerId, side: 'HOME' as const, isSelf: false }] : []),
              ...opponentIds.map((playerId) => ({
                playerId,
                side: 'AWAY' as const,
                isSelf: false,
              })),
            ],
          },
          tags: { create: tags },
        },
      });

      totalMatches += 1;
    }
  }

  // --- Goals ---------------------------------------------------------------
  const yearStart = new Date(Date.UTC(today.getUTCFullYear(), 0, 1));
  await prisma.goal.createMany({
    data: [
      {
        userId: user.id,
        title: 'Play 150 matches this year',
        metric: 'MATCHES_PLAYED',
        targetValue: 150,
        startsOn: yearStart,
        deadline: new Date(Date.UTC(today.getUTCFullYear(), 11, 31)),
        notes: DEMO_MARKER,
      },
      {
        userId: user.id,
        title: 'Reach a 60% win rate',
        metric: 'WIN_RATE',
        targetValue: 60,
        startsOn: yearStart,
        notes: DEMO_MARKER,
      },
      {
        userId: user.id,
        title: 'Win 8 matches in a row',
        metric: 'WIN_STREAK',
        targetValue: 8,
        startsOn: yearStart,
        notes: DEMO_MARKER,
      },
      {
        userId: user.id,
        title: 'Lift singles win rate to 55%',
        metric: 'WIN_RATE',
        targetValue: 55,
        discipline: 'SINGLES',
        startsOn: yearStart,
        deadline: new Date(today.getTime() + 60 * 86_400_000),
        notes: DEMO_MARKER,
      },
    ],
  });

  // --- Derived projections -------------------------------------------------
  // Ratings are rebuilt from the seeded matches by the same replay the API uses, so the
  // seed cannot produce a state the application would never create itself.
  const matches = await prisma.match.findMany({
    where: { userId: user.id },
    include: {
      games: { orderBy: { gameNumber: 'asc' } },
      participants: true,
      tags: true,
      session: { select: { sessionType: true, venueId: true } },
    },
    orderBy: { playedAt: 'asc' },
  });

  const replay = replayRatings(
    matches.map((match) => ({
      id: match.id,
      sessionId: match.sessionId,
      playedAt: match.playedAt,
      orderInSession: match.orderInSession,
      discipline: match.discipline,
      sessionType: match.session.sessionType,
      venueId: match.session.venueId,
      venueName: null,
      scoring: {
        pointsToWin: match.pointsToWin,
        winBy: match.winBy,
        maxPoints: match.maxPoints,
        bestOf: match.bestOf,
      },
      durationSeconds: match.durationSeconds,
      difficulty: match.difficulty,
      tags: match.tags.map((tag) => tag.tag),
      partnerIds: match.participants
        .filter((participant) => participant.side === 'HOME' && !participant.isSelf)
        .map((participant) => participant.playerId),
      opponentIds: match.participants
        .filter((participant) => participant.side === 'AWAY')
        .map((participant) => participant.playerId),
      games: match.games.map((game) => ({
        myScore: game.myScore,
        opponentScore: game.opponentScore,
      })),
    })),
  );

  await prisma.ratingEvent.createMany({
    data: replay.events.map((event) => ({
      userId: user.id,
      matchId: event.matchId,
      discipline: event.discipline,
      playedAt: event.playedAt,
      ratingBefore: event.ratingBefore,
      ratingAfter: event.ratingAfter,
      delta: event.delta,
      opponentRating: event.opponentRating,
      kFactor: event.kFactor,
      result: event.result,
    })),
  });

  for (const [playerId, state] of replay.playerRatings) {
    await prisma.player.update({
      where: { id: playerId },
      data: { rating: state.rating, ratingDeviation: ratingDeviation(state.matches) },
    });
  }
  await prisma.player.update({
    where: { id: self.id },
    data: {
      rating: replay.userRating.rating,
      ratingDeviation: ratingDeviation(replay.userRating.matches),
    },
  });

  const wins = matches.filter((match) => match.result === 'WIN').length;

  console.info(`
Seed complete — THIS IS DEMO DATA, NOT REAL RESULTS.

  Sign in with:  ${DEMO_EMAIL}
  Password:      ${DEMO_PASSWORD}

  ${people.length} players, ${venues.length} venues
  ${dayOffsets.length} sessions, ${totalMatches} matches (${wins} wins, ${totalMatches - wins} losses)
  Rating after replay: ${replay.userRating.rating}
`);
}

main()
  .catch((error: unknown) => {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
